#!/usr/bin/env python3
"""
NMRK Indicative Valuation Tool — Address-Based CLI
====================================================
Usage:
    python nmrk_indicative_valuation_by_address.py
    python nmrk_indicative_valuation_by_address.py --address "BISHAN 8" --unit "#12-34"

Requirements:
    pip install pandas numpy scikit-learn openpyxl requests

Files needed in the same folder as this script:
    rf_model.pkl              — Trained model (run nmrk_train_model.py once to generate)
    postal_lookup.csv         — Postal code lookup table (provided)
    Non-Landed-Caveats.xlsx   — Original dataset (for re-fitting label encoders)
    predictions_sample.csv    — Residuals file (auto-generated by training script)

Author  : NMRK Research
Version : 1.1
"""

import os, sys, re, json, argparse, warnings
from pathlib import Path
from datetime import datetime

warnings.filterwarnings("ignore")

# ── Configuration ─────────────────────────────────────────────────────────────
# All files are expected in the same folder as this script.
# To use a different folder, set the NMRK_WORKSPACE environment variable.

WORKSPACE = Path(os.environ.get("NMRK_WORKSPACE", Path(__file__).parent))

MODEL_PATH        = MODEL_PATH = Path(r"C:\Users\SW154611\NMRK Tenant (8209549)\Newmark SG Research - Documents\Research\Joshua Random Scripts\rf_model.pkl")
POSTAL_LOOKUP_CSV = WORKSPACE / "postal_lookup.csv"
DATASET_PATH      = Path(r"C:\Users\SW154611\NMRK Tenant (8209549)\Newmark SG Research - Documents\Research\For Valuation\Non-Landed Caveats.xlsx")
PREDICTIONS_CSV   = WORKSPACE / "predictions_sample.csv"
SHAP_CSV          = WORKSPACE / "shap_importance.csv"

ONEMAP_SEARCH_URL = (
    "https://www.onemap.gov.sg/api/common/elastic/search"
    "?searchVal={query}&returnGeom=Y&getAddrDetails=Y&pageNum=1"
)

# Categorical columns — must match training order exactly
CAT_COLS = [
    "Project Name", "Type of Sale", "Type of Area", "Property Type",
    "Purchaser Address Indicator", "Planning Region", "Planning Area",
    "Market segment", "Tenure Group", "Completion Bucket",
]

# Feature order as stored in model.feature_names_in_
FEATURE_COLS = [
    "Project Name", "Area (SQFT)", "Type of Sale", "Type of Area",
    "Property Type", "Purchaser Address Indicator", "Planning Region",
    "Planning Area", "Market segment", "Sale Year", "Sale Month",
    "Sale Quarter", "Floor Level", "Tenure Group", "Completion Bucket",
]

# ── Terminal colour helpers ───────────────────────────────────────────────────

def _bold(t):   return f"\033[1m{t}\033[0m"
def _green(t):  return f"\033[32m{t}\033[0m"
def _yellow(t): return f"\033[33m{t}\033[0m"
def _cyan(t):   return f"\033[36m{t}\033[0m"
def _red(t):    return f"\033[31m{t}\033[0m"

def banner():
    print()
    print(_bold("=" * 60))
    print(_bold("  NMRK Indicative Valuation Tool  |  Singapore Residential"))
    print(_bold("=" * 60))
    print()

# ── Interactive prompt ────────────────────────────────────────────────────────

def prompt(question, default=None, choices=None, free_text=False):
    """Prompt with optional default and choice validation."""
    hint = ""
    if choices and not free_text:
        hint = f"  [{' / '.join(choices)}]"
    if default is not None:
        hint += f"  (default: {default})"
    while True:
        raw = input(f"  {question}{hint}: ").strip()
        if not raw and default is not None:
            return str(default)
        if raw and free_text:
            return raw
        if raw and choices:
            matches = [c for c in choices if c.lower().startswith(raw.lower())]
            if len(matches) == 1:
                return matches[0]
            elif len(matches) > 1:
                print(_yellow(f"    Ambiguous — did you mean: {', '.join(matches)}?"))
                continue
            else:
                # Allow exact match regardless of case
                exact = [c for c in choices if c.lower() == raw.lower()]
                if exact:
                    return exact[0]
                print(_yellow(f"    Invalid. Choose from: {', '.join(choices)}"))
                continue
        if raw:
            return raw
        print(_yellow("    Please enter a value."))

# ── Step 1: OneMap address lookup ─────────────────────────────────────────────

def onemap_search(query: str) -> list:
    import requests
    url = ONEMAP_SEARCH_URL.format(query=query.replace(" ", "+"))
    try:
        resp = requests.get(url, timeout=10)
        resp.raise_for_status()
        return resp.json().get("results", [])
    except Exception as e:
        print(_yellow(f"    [Warning] OneMap API error: {e}"))
        return []

def resolve_address(address_query: str) -> dict:
    """
    Query OneMap. Returns dict with POSTAL, BUILDING, ADDRESS, LATITUDE, LONGITUDE.
    Returns None if nothing found.
    """
    results = onemap_search(address_query)
    if not results:
        return None

    if len(results) == 1:
        chosen = results[0]
    else:
        print(f"\n  Found {len(results)} matching addresses:")
        for i, r in enumerate(results[:10], 1):
            print(f"    {i}. {r.get('ADDRESS', 'N/A')}  [Postal: {r.get('POSTAL', '?')}]")
        while True:
            sel = input(f"\n  Select (1-{min(len(results), 10)}, or 0 to enter postal manually): ").strip()
            if sel == "0":
                return None
            try:
                idx = int(sel) - 1
                if 0 <= idx < min(len(results), 10):
                    chosen = results[idx]
                    break
            except ValueError:
                pass
            print(_yellow("    Invalid selection."))

    postal = chosen.get("POSTAL", "").strip()
    if not postal or postal == "NIL":
        postal = None

    return {
        "POSTAL"   : postal,
        "BUILDING" : chosen.get("BUILDING", chosen.get("SEARCHVAL", "Unknown")),
        "ADDRESS"  : chosen.get("ADDRESS", ""),
        "LATITUDE" : float(chosen.get("LATITUDE", 0) or 0),
        "LONGITUDE": float(chosen.get("LONGITUDE", 0) or 0),
    }

# ── Step 2: Postal lookup ─────────────────────────────────────────────────────

def load_postal_lookup() -> dict:
    import pandas as pd
    if not POSTAL_LOOKUP_CSV.exists():
        raise FileNotFoundError(
            f"postal_lookup.csv not found at: {POSTAL_LOOKUP_CSV}\n"
            "Download it from Perplexity and place it in the same folder as this script."
        )
    ldf = pd.read_csv(POSTAL_LOOKUP_CSV, dtype={"Postal Code": str})
    ldf["Postal Code"] = ldf["Postal Code"].str.zfill(6)
    return ldf.set_index("Postal Code").to_dict("index")

# ── Step 3: Floor level from unit number ──────────────────────────────────────

def extract_floor(unit_number: str) -> int:
    """#12-34 → 12, #B1-05 → 0, 25-10 → 25"""
    s = unit_number.strip().lstrip("#").upper()
    if s.startswith("B"):
        return 0
    m = re.match(r"^(\d+)", s)
    return int(m.group(1)) if m else 0

# ── Step 4: Load model ────────────────────────────────────────────────────────

def load_model():
    import pickle
    if not MODEL_PATH.exists():
        raise FileNotFoundError(
            f"\nrf_model.pkl not found at: {MODEL_PATH}\n\n"
            "You need to train the model first. Run:\n"
            "    python nmrk_train_model.py\n\n"
            "Make sure Non-Landed-Caveats.xlsx is in the same folder, then re-run this script."
        )
    print(f"  Loading model …", end=" ", flush=True)
    with open(MODEL_PATH, "rb") as f:
        model = pickle.load(f)
    print(_green("OK"))
    return model

# ── Step 5: Label encoders (refit from dataset) ───────────────────────────────

def build_label_encoders(verbose=True) -> dict:
    import pandas as pd
    from sklearn.preprocessing import LabelEncoder

    if not DATASET_PATH.exists():
        raise FileNotFoundError(
            f"\nNon-Landed-Caveats.xlsx not found at: {DATASET_PATH}\n"
            "Place the dataset in the same folder as this script."
        )

    if verbose:
        print(f"  Re-fitting label encoders …", end=" ", flush=True)

    df = pd.read_excel(
        DATASET_PATH,
        sheet_name="Non landed caveats excluding EC",
        usecols=[
            "Project Name", "Type of Sale", "Type of Area", "Property Type",
            "Purchaser Address Indicator", "Planning Region", "Planning Area",
            "Market segment", "Tenure", "Completion Date",
        ],
    )

    def simplify_tenure(t):
        t = str(t).lower()
        if "freehold" in t: return "Freehold"
        if "999" in t:      return "999-yr"
        if "99" in t:       return "99-yr"
        return "Other"

    def completion_bucket(c):
        c = str(c).strip().lower()
        if "uncompleted" in c: return "Uncompleted"
        try:
            yr = int(c[:4])
            if yr < 2000: return "Pre-2000"
            if yr < 2010: return "2000-2009"
            if yr < 2020: return "2010-2019"
            return "2020+"
        except:
            return "Unknown"

    df["Tenure Group"]      = df["Tenure"].apply(simplify_tenure)
    df["Completion Bucket"] = df["Completion Date"].apply(completion_bucket)
    df.drop(columns=["Tenure", "Completion Date"], inplace=True)

    le_dict = {}
    for col in CAT_COLS:
        df[col] = df[col].fillna("Unknown").astype(str)
        le = LabelEncoder()
        le.fit(df[col])
        le_dict[col] = le

    if verbose:
        print(_green("OK"))
    return le_dict

def encode_value(le, value: str, col_name: str) -> int:
    val = str(value)
    classes = list(le.classes_)
    if val in classes:
        return int(le.transform([val])[0])
    lower_map = {c.lower(): c for c in classes}
    if val.lower() in lower_map:
        return int(le.transform([lower_map[val.lower()]])[0])
    if "Unknown" in classes:
        print(_yellow(f"\n    [Warning] '{val}' not in training data for '{col_name}'. Using 'Unknown'."))
        return int(le.transform(["Unknown"])[0])
    return 0

# ── Step 6: 95% CI from residuals ─────────────────────────────────────────────

def compute_residual_offsets():
    import numpy as np
    import pandas as pd
    if PREDICTIONS_CSV.exists():
        pdf = pd.read_csv(PREDICTIONS_CSV)
        pred_col   = next((c for c in pdf.columns if "Predicted" in c), None)
        actual_col = next((c for c in pdf.columns if "Actual"    in c), None)
        if pred_col and actual_col:
            residuals = pdf[pred_col] - pdf[actual_col]
            return float(np.percentile(residuals, 2.5)), float(np.percentile(residuals, 97.5))
    return None, None

# ── SHAP top factors ──────────────────────────────────────────────────────────

def top_shap_factors():
    if SHAP_CSV.exists():
        import pandas as pd
        sdf = pd.read_csv(SHAP_CSV).head(8)
        return list(zip(sdf.iloc[:, 0], sdf.iloc[:, 1]))
    return []

# ── Main valuation ────────────────────────────────────────────────────────────

def run_valuation(address_str: str, unit_str: str) -> dict:
    import numpy as np
    import pandas as pd

    # ── Step 1: Address → postal ──────────────────────────────────────────────
    print()
    print(_bold("── Step 1: Address Lookup ──────────────────────────────────"))
    print(f"  Querying OneMap for: {_cyan(address_str)} …")
    addr_info = resolve_address(address_str)

    if addr_info is None:
        print(_yellow("  Not found via OneMap. Enter postal code manually."))
        postal_input = input("  6-digit postal code: ").strip().zfill(6)
        addr_info = {
            "POSTAL": postal_input, "BUILDING": "Unknown",
            "ADDRESS": address_str, "LATITUDE": 0.0, "LONGITUDE": 0.0,
        }
    else:
        print(f"  {_green('Found')} : {addr_info['ADDRESS']}")
        print(f"  Postal   : {addr_info['POSTAL'] or 'N/A'}")
        print(f"  Building : {addr_info['BUILDING']}")

    # ── Step 2: Postal → property attributes ──────────────────────────────────
    print()
    print(_bold("── Step 2: Property Attributes ─────────────────────────────"))
    postal_dict = load_postal_lookup()
    prop_attrs  = lookup_postal(addr_info["POSTAL"], postal_dict) if addr_info["POSTAL"] else None

    if prop_attrs:
        print(f"  Project Name      : {_cyan(prop_attrs['Project Name'])}")
        print(f"  Planning Area     : {prop_attrs['Planning Area']}, {prop_attrs['Planning Region']}")
        print(f"  Market Segment    : {prop_attrs['Market segment']}")
        print(f"  Property Type     : {prop_attrs['Property Type']}")
        print(f"  Tenure            : {prop_attrs['Tenure Group']}")
        print(f"  Completion Period : {prop_attrs.get('Completion Bucket', 'Unknown')}")
    else:
        print(_yellow("  Postal not in lookup. Enter details manually."))
        prop_attrs = {
            "Project Name"     : prompt("Project Name (e.g. BISHAN 8)", free_text=True),
            "Planning Region"  : prompt("Planning Region", choices=["Central Region","East Region","North Region","North-East Region","West Region"]),
            "Planning Area"    : prompt("Planning Area (e.g. Bishan)", free_text=True),
            "Market segment"   : prompt("Market Segment", choices=["CCR", "RCR", "OCR"]),
            "Property Type"    : prompt("Property Type", choices=["Apartment", "Condominium", "Executive Condominium"]),
            "Tenure Group"     : prompt("Tenure", choices=["Freehold", "999-yr", "99-yr", "Other"]),
            "Completion Bucket": prompt("Completion Period", default="2010-2019",
                                        choices=["Pre-2000","2000-2009","2010-2019","2020+","Uncompleted"]),
        }

    # Completion Bucket: use from lookup, or ask only if missing/Unknown
    completion_b = prop_attrs.get("Completion Bucket", "Unknown")
    if completion_b in ("Unknown", "", None):
        completion_b = prompt("Completion Period", default="2010-2019",
                              choices=["Pre-2000","2000-2009","2010-2019","2020+","Uncompleted"])

    # ── Step 3: Unit details ──────────────────────────────────────────────────
    print()
    print(_bold("── Step 3: Unit Details ────────────────────────────────────"))
    floor_level = extract_floor(unit_str)
    print(f"  Unit Number       : {unit_str}  →  Floor {floor_level}")

    # ── Step 4: Sale details (minimal inputs) ─────────────────────────────────
    print()
    print(_bold("── Step 4: Sale Details ────────────────────────────────────"))
    print("  (Press Enter to accept defaults)")
    print()

    now = datetime.now()
    area_sqft    = float(prompt("Area (sqft)", default="1000", free_text=True))
    type_of_sale = prompt("Type of Sale", default="Resale",
                          choices=["New Sale", "Resale", "Sub Sale"])
    sale_year    = int(prompt("Sale Year",    default=str(now.year), free_text=True))
    sale_month   = int(prompt("Sale Month (1-12)", default=str(now.month), free_text=True))

    sale_quarter = (sale_month - 1) // 3 + 1

    # Fixed defaults (not asked — almost always Strata / Private for condo buyers)
    type_of_area = "Strata"
    buyer_addr   = "Private"

    # ── Step 5: Model inference ───────────────────────────────────────────────
    print()
    print(_bold("── Step 5: Model Inference ─────────────────────────────────"))
    model   = load_model()
    le_dict = build_label_encoders(verbose=True)

    row = {
        "Project Name"               : prop_attrs["Project Name"],
        "Area (SQFT)"                : area_sqft,
        "Type of Sale"               : type_of_sale,
        "Type of Area"               : type_of_area,
        "Property Type"              : prop_attrs["Property Type"],
        "Purchaser Address Indicator": buyer_addr,
        "Planning Region"            : prop_attrs["Planning Region"],
        "Planning Area"              : prop_attrs["Planning Area"],
        "Market segment"             : prop_attrs["Market segment"],
        "Tenure Group"               : prop_attrs["Tenure Group"],
        "Completion Bucket"          : completion_b,
        "Sale Year"                  : sale_year,
        "Sale Month"                 : sale_month,
        "Sale Quarter"               : sale_quarter,
        "Floor Level"                : floor_level,
    }

    print("  Encoding features …", end=" ", flush=True)
    encoded = {}
    for col in FEATURE_COLS:
        if col in CAT_COLS:
            encoded[col] = encode_value(le_dict[col], row[col], col)
        else:
            encoded[col] = row[col]
    print(_green("OK"))

    X_input  = pd.DataFrame([encoded])[FEATURE_COLS]
    print("  Running prediction …", end=" ", flush=True)
    psf_pred    = float(model.predict(X_input)[0])
    total_price = psf_pred * area_sqft
    print(_green("OK"))

    # 95% CI
    res_lo, res_hi = compute_residual_offsets()
    if res_lo is not None:
        psf_lo, psf_hi = psf_pred + res_lo, psf_pred + res_hi
    else:
        psf_lo, psf_hi = psf_pred * 0.95, psf_pred * 1.05

    total_lo = psf_lo * area_sqft
    total_hi = psf_hi * area_sqft

    # ── Results ───────────────────────────────────────────────────────────────
    print()
    print(_bold("=" * 60))
    print(_bold("  INDICATIVE VALUATION RESULT"))
    print(_bold("=" * 60))
    print()
    print(f"  Property          : {_cyan(prop_attrs['Project Name'])}")
    print(f"  Address           : {addr_info['ADDRESS']}")
    print(f"  Unit              : {unit_str}  (Floor {floor_level})")
    print(f"  Area              : {area_sqft:,.0f} sqft")
    print(f"  Location          : {prop_attrs['Planning Area']}, {prop_attrs['Planning Region']}")
    print(f"  Market Segment    : {prop_attrs['Market segment']}")
    print(f"  Tenure            : {prop_attrs['Tenure Group']}")
    print(f"  Completion Period : {completion_b}")
    print(f"  Sale Type         : {type_of_sale}  ({sale_year} Q{sale_quarter})")
    print()
    print(f"  {'Unit Price (PSF)':<24}: {_bold(_green(f'S${psf_pred:,.0f}'))}")
    print(f"  {'Total Value':<24}: {_bold(_green(f'S${total_price:,.0f}'))}")
    print()
    print(f"  {'95% CI  PSF':<24}: S${psf_lo:,.0f}  –  S${psf_hi:,.0f}")
    print(f"  {'95% CI  Total':<24}: S${total_lo:,.0f}  –  S${total_hi:,.0f}")
    print()

    # SHAP factors (if available)
    factors = top_shap_factors()
    if factors:
        print(_bold("  Top Pricing Drivers (SHAP):"))
        for name, impact in factors[:6]:
            bar = "█" * min(int(impact / 25), 20)
            print(f"    {name:<36} {_cyan(bar)}  ±{impact:.0f} psf")
        print()

    print(_bold("=" * 60))
    print(_yellow("  Indicative estimate only. Not a formal valuation."))
    print(_yellow("  Model: RandomForest  |  R²=0.965  |  MAE=S$68 psf"))
    print(_bold("=" * 60))
    print()

    return {
        "address"      : addr_info["ADDRESS"],
        "postal"       : addr_info["POSTAL"],
        "unit"         : unit_str,
        "floor"        : floor_level,
        "area_sqft"    : area_sqft,
        "project"      : prop_attrs["Project Name"],
        "segment"      : prop_attrs["Market segment"],
        "region"       : prop_attrs["Planning Region"],
        "area_name"    : prop_attrs["Planning Area"],
        "tenure"       : prop_attrs["Tenure Group"],
        "completion"   : completion_b,
        "psf_pred"     : round(psf_pred, 2),
        "psf_lo"       : round(psf_lo, 2),
        "psf_hi"       : round(psf_hi, 2),
        "total_pred"   : round(total_price, 2),
        "total_lo"     : round(total_lo, 2),
        "total_hi"     : round(total_hi, 2),
        "sale_year"    : sale_year,
        "sale_month"   : sale_month,
        "type_of_sale" : type_of_sale,
    }

def lookup_postal(postal_code: str, postal_dict: dict):
    return postal_dict.get(str(postal_code).zfill(6))

# ── Interactive mode ──────────────────────────────────────────────────────────

def interactive_mode():
    banner()
    print("  Enter a property address to get an indicative valuation.")
    print("  Powered by URA caveats data  |  RandomForest R²=0.965")
    print()

    while True:
        print(_bold("── Property Address ────────────────────────────────────────"))
        address_input = prompt("Address or project name (e.g. 'BISHAN 8')", free_text=True)
        unit_input    = prompt("Unit number (e.g. #12-34)", free_text=True)

        try:
            run_valuation(address_input, unit_input)
        except FileNotFoundError as e:
            print(_red(f"\n  {e}\n"))
        except KeyboardInterrupt:
            print("\n  Interrupted.")
            break
        except Exception as e:
            import traceback
            print(_red(f"\n  Error: {e}"))
            traceback.print_exc()

        again = input("  Run another valuation? [y/N]: ").strip().lower()
        if again not in ("y", "yes"):
            break

    print("\n  Thank you for using the NMRK Indicative Valuation Tool.\n")

# ── CLI ───────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="NMRK Indicative Valuation Tool — Singapore Residential",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python nmrk_indicative_valuation_by_address.py
  python nmrk_indicative_valuation_by_address.py --address "BISHAN 8" --unit "#12-34"
  python nmrk_indicative_valuation_by_address.py --address "Orchard Boulevard" --unit "#25-01" --json
        """
    )
    parser.add_argument("--address", type=str, help="Address or project name")
    parser.add_argument("--unit",    type=str, help="Unit number (e.g. #12-34)")
    parser.add_argument("--json",    action="store_true", help="Output result as JSON")
    args = parser.parse_args()

    if args.address and args.unit:
        banner()
        result = run_valuation(args.address, args.unit)
        if args.json:
            print(json.dumps(result, indent=2))
    else:
        interactive_mode()

if __name__ == "__main__":
    main()
